name: Build App

on:
  workflow_dispatch:
  #push:
  #pull_request:

env:
  ORG_ID: d69c815b-930b-48f9-898e-c7dbbfc98242
  SIGNIN_POLICY_SLUG: e2e-test-sp
  PROJECT_SLUG: e2e-gha-test-project
  CONNECTOR_URL: https://cshqlrl4-44353.euw.devtunnels.ms/
  ARTIFACT_CONFIGURATION_SLUG: exe-in-zip



jobs:
  build:
    permissions:
      actions: read  # get run data
      #checks: write
      contents: read  # do checkout
      # deployments: write
      # id-token: write
      # issues: write
      # discussions: write
      # packages: write
      # pages: write
      # repository-projects: write
      # statuses: write

    runs-on: windows-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v3

    - name: Upload the artifcat file
      uses: actions/upload-artifact@v4
      with: 
        name: original-artifact
        path: "./files/hello-world.exe"
    
    - name: Run submit signing request for FQA ORG1
      id: submit_sr
      uses: signpath/github-action-submit-signing-request@v0.3
      with:
        connector-url: '${{ env.CONNECTOR_URL }}'
        api-token: '${{ secrets.SIGN_PATH_API_TOKEN }}'
        organization-id: '${{ env.ORG_ID }}'
        project-slug: '${{ env.PROJECT_SLUG }}'
        signing-policy-slug: '${{ env.SIGNIN_POLICY_SLUG }}'
        artifact-configuration-slug: '${{ env.ARTIFACT_CONFIGURATION_SLUG }}'
        github-artifact-name: original-artifact
        service-unavailable-timeout-in-seconds: 20
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        wait-for-completion: true
        output-artifact-directory: 'org1/content'

    - uses: actions/download-artifact@v4
      with:
        name: original-artifact
        path: org1/content2

    # - name: Sleep for 30 seconds
    #   run: Start-Sleep -s 300
    #   shell: powershell

    - uses: actions/upload-artifact@v4
      with: 
        name: Org1SignedArtifact
        path: "org1"


    - name: Log submit-signing-request task output
      run: |
           echo "signing-request-id [${{steps.submit_sr.outputs.signing-request-id }}]"
           echo "signing-request-web-url [${{steps.submit_sr.outputs.signing-request-web-url }}]"
           echo "signpath-api-url [${{steps.submit_sr.outputs.signpath-api-url }}]"
           echo "signed-artifact-download-url [${{steps.submit_sr.outputs.signed-artifact-download-url }}]"
