name: Test PROD Deployment

on:
 push:
 pull_request:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Log workflow version
      run: "echo \"Version 1\""

    - name: checkout
      uses: actions/checkout@v3
     
    # - uses: suisei-cn/actions-download-file@v1.4.0
      # id: downloadfile  # Remember to give an ID if you need the output
      # name: Download big file
      # with:
        # url: "https://www.rubicon.eu/downloads/26bb711a-5771-49fb-b41c-cdb2e48243ee/SFX_512MB.exe"
        
    - name: Upload the artifcat file
      uses: actions/upload-artifact@v3
      with: 
        name: original-artifact
        path: "./files/hello-world.exe"
     
    - name: check if connector is accessible
      uses: satak/webrequest-action@master
      with:
        url: https://githubactions.connectors.fqa.test.signpath.io:15021/healthz
        method: GET    
    - name: check if SignPath is accessible
      uses: satak/webrequest-action@master
      with:
        url: https://fqa.test.signpath.io/api/healthz
        method: GET
    - name: Run submit signing request for FQA ORG1
      id: "submit_with_download_org1"
      uses: SignPath/github-actions/actions/submit-signing-request@main
      with:
        #connector-url: 'https://githubactions.connectors.signpath.io'
        connector-url: 'https://gttwks4r-44353.euw.devtunnels.ms/'
        api-token: '${{ secrets.SIGN_PATH_API_TOKEN_PROD_DEMO_ORG }}'
        organization-id: 'caa5e4fa-f3ca-431b-8888-67952847b3e6'
        project-slug: 'Executable'
        # this SigningPolicy has auto-approve enabled, so you don't need to approve the signing request
        signing-policy-slug: 'test-signing'
        artifact-configuration-slug: 'initial'
        artifact-name: original-artifact
        github-token: '${{ secrets.GHA_TOKEN }}'
        signed-artifact-destination-path: 'hello-world-signed.exe'
    
    - name: Upload the artifact signed by Org1
      uses: actions/upload-artifact@v3
      with: 
        name: Org1SignedArtifact
        path: "hello-world-signed.exe"

    - name: Log submit-signing-request task output for Org1
      run: |
           echo "signing-request-id [${{steps.submit_with_download_org1.outputs.signing-request-id }}]"
           echo "signing-request-web-url [${{steps.submit_with_download_org1.outputs.signing-request-web-url }}]"
           echo "signpath-api-url [${{steps.submit_with_download_org1.outputs.signpath-api-url }}]"
           echo "signed-artifact-download-url [${{steps.submit_with_download_org1.outputs.signed-artifact-download-url }}]"
