name: e2e Happy Path Test Workflow

on:
    workflow_dispatch:
        inputs:
            connector-url:
              required: true
              type: string

jobs:
    build:
      permissions:
        actions: read  # get run data
        contents: read  # do checkout
      runs-on: windows-latest
  
      steps:
        - run: |
            echo "Connector Url: ${{ inputs.connector-url }}"

